In [7]:
import numpy as np
from scipy import linalg 

In [3]:
# 6.1) Решите линейную систему
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)
print(f'Result: {X}')

array([-9.2       ,  0.9       ,  6.46666667])

In [5]:
# 6.2) Найдите псевдорешение
A = np.array([[1, 2], [3, -4], [8, -5]])
B = np.array([4, 1, 10])
X = np.linalg.lstsq(A, B)
print(f'Result: {X}')

Result: (array([1.94578313, 1.13975904]), array([0.14578313]), 2, array([10.56219965,  2.72762507]))


/Users/ignorant/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


(array([1.94578313, 1.13975904]),
 array([0.14578313]),
 2,
 array([10.56219965,  2.72762507]))

In [10]:
# 6.3) 

P = [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U = [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
Result: (array([1.94578313, 1.13975904]), array([0.14578313]), 2, array([10.56219965,  2.72762507]))


In [11]:
# 6.4) Вычислите LU-разложение матрицы
A = np.array([[ 1,  2,  3],
              [ 2, 16, 21],
              [ 4, 28, 73]])
P, L, U = linalg.lu(A)

print(f'P = {P}')
print(f'L = {L}')
print(f'U = {U}')

# --------------------
B = np.array([6, 0, 2])
X = np.linalg.solve(A, B)
print(f'Result: {X}')

P = [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U = [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
Result: (array([1.94578313, 1.13975904]), array([0.14578313]), 2, array([10.56219965,  2.72762507]))


In [12]:
# 6.5) Найдите нормальное псевдорешение недоопределенной системы
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
X = np.linalg.lstsq(A, B)
print(f'Result: {X}')

Result: (array([ 1.38191882, -0.18081181,  0.0202952 ]), array([], dtype=float64), 2, array([9.65316119, 2.41173777]))


/Users/ignorant/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.
